### ISSUE TITLE
YouTube playlist should have Longest Johns’ Santiana

### ISSUE THREAD

**Issue by c-harding** [RcColes/UBES-songbook#1]
The Fisherman’s Friends version has substantially different lyrics. This one should match the document and the Spotify version exactly: https://music.youtube.com/watch?v=xsrRncY3D38

**Comment by RcColes** [comment]
Yeah this was a tricky one - its really unfortunate that the Longest Johns don't have much on YTM

I was originally trying to avoid live performances for the music - This one notable has the person filming laughing loudly. I suspect this should be deprioritised though in favour of getting the lyrics consistent.

I'll put checking the others on my TODO list

**Comment by RcColes** [comment]
I've swapped it out for the one you suggested

**Comment by c-harding** [comment]
Santiana has disappeared from the YouTube playlist. Alternative version: <https://music.youtube.com/watch?v=laY4TcWEbSA>.

**Comment by RcColes** [comment]
I can still see (and play) Santiana in that playlist

**Comment by RcColes** [comment]
Ah no maybe I can't
